AWSTemplateFormatVersion: '2010-09-09'
Description: 'Real-Time Fraud Detection - Lambda Producer'

Parameters:
  Environment:
    Type: String
    Description: Environment name
    Default: dev
  
  FoundationStackName:
    Type: String
    Description: Name of the foundation stack
    Default: dev-rtfd-streaming-foundation

Resources:
  
  ProducerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 
        - '${Env}-rtfd-producer-${Suffix}'
        - Env: !Ref Environment
          Suffix: 
            Fn::ImportValue: !Sub '${FoundationStackName}-UniqueSuffix'
      Runtime: python3.12
      Handler: lambda_function.lambda_handler
      Role: 
        Fn::ImportValue: !Sub '${FoundationStackName}-ProducerRole'
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          KINESIS_STREAM_NAME:
            Fn::ImportValue: !Sub '${FoundationStackName}-TransactionStream'
          BATCH_SIZE: '100'
          MAX_RECORDS: '500'
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Placeholder - deploy with package'}
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: rtfd
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  ProducerLambdaArn:
    Description: Producer Lambda ARN
    Value: !GetAtt ProducerLambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ProducerLambdaArn'
  
  ProducerLambdaName:
    Description: Producer Lambda function name
    Value: !Ref ProducerLambdaFunction
    Export:
      Name: !Sub '${AWS::StackName}-ProducerLambdaName'